"""Constants for the NerdAxe Miner integration."""

DOMAIN = "nerdaxe_miner"

CONF_HISTORY_ENABLED = "history_enabled"
CONF_HISTORY_MAX_MB = "history_max_mb"
CONF_HISTORY_RAW_KEEP_DAYS = "history_raw_keep_days"
CONF_HISTORY_STORE_RAW_PAYLOAD = "history_store_raw_payload"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_SCAN_INTERVAL = 10
MIN_SCAN_INTERVAL = 5
MAX_SCAN_INTERVAL = 300

DEFAULT_HISTORY_ENABLED = False
DEFAULT_HISTORY_MAX_MB = 512
DEFAULT_HISTORY_RAW_KEEP_DAYS = 30
DEFAULT_HISTORY_STORE_RAW_PAYLOAD = False
DEFAULT_TIMEOUT_SECONDS = 10

INFO_PATH = "/api/system/info"
RESTART_PATH = "/api/system/restart"
RECORDER_DIR_NAME = "nerdaxe_recorder"

OPTIONS_DEFAULTS = {
    CONF_SCAN_INTERVAL: DEFAULT_SCAN_INTERVAL,
    CONF_HISTORY_ENABLED: DEFAULT_HISTORY_ENABLED,
    CONF_HISTORY_MAX_MB: DEFAULT_HISTORY_MAX_MB,
    CONF_HISTORY_RAW_KEEP_DAYS: DEFAULT_HISTORY_RAW_KEEP_DAYS,
    CONF_HISTORY_STORE_RAW_PAYLOAD: DEFAULT_HISTORY_STORE_RAW_PAYLOAD,
}
